# Generated by Django 4.2 on 2023-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='title_en_us',
            field=models.CharField(help_text='название категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(help_text='название категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='title_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='record',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='название категории', max_length=64, unique=True),
        ),
    ]
