# Generated by Django 4.2 on 2023-07-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='full_text_en_us',
            field=models.TextField(null=True, verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='record',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Статья'),
        ),
    ]
